import { Poppins } from "next/font/google";
import { redirect } from "next/navigation";
import "../globals.css";
import { getCurrentUser } from "@/actions/shared";
import { Toaster } from "react-hot-toast";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "500", "600", "700"],
});
export const metadata = {
  title: "Page Creation",
  description: "Generated by Next.js",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { session } = await getCurrentUser();
  if (!session) {
    redirect(`/sign-up`);
  }
  return (
    <html lang="en">
      <body
        className={`${poppins.className} min-h-screen bg-gray-200 text-dark`}
      >
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
