import { auth } from "@/auth";
// import { db } from "@/db";
import { Session } from "next-auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Reach me",
  description: "Generated by Next.js",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: Session | null = await auth();
  // const page = await db.page.findUnique({
  //   where: {
  //     userId: session?.user?.id,
  //   },
  // });
  console.log();
  if (!session?.user) {
    redirect("/");
  }

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
