version: "3"
services:
  postgresdb:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    env_file:
      - .env
    restart: always
    container_name: postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgresdb
    ports:
      - 8081:8080
volumes:
  pgdata:
