version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: developement
    container_name: nextApp
    depends_on: [nginx]
    restart: always
    ports:
      - 3000:3000

  postgres:
    image: postgres:16-alpine
    env_file: ./.env
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8081
    container_name: adminer

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
volumes:
  postgres:
