version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    container_name: app

  db:
    restart: always
    container_name: postgres_db
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  data:
